### ISSUE TITLE
Checkpoint #2 ready for review

### ISSUE THREAD

**Issue by Rashad-636** [Rashad-636/sportsPerformancePredictor#2]
My database is designed and cerated with the necessary relationships (I hope?). 
Sport and SportDaotest created and unit tested

Also, could you look at my log4J properties? my log file is creating so many different files, how can I stop this?

**Comment by pawaitemadisoncollege** [comment]
Hi @Rashad-636 ! You've made some good early progress with your indie project!  My notes from a review of your project for checkpoint 2 are below. In general you've hit the mark and are in a really good position for this point in the semester. Most of comments below are related to things to keep in mind for completion in the near future, the only one required for "met" completion is related to the ERD:

**Database designed and created** 

I can see sql for your database, which looks from what I can tell. The user table may not be represented yet. It would be easier for me to review if I can look at an ERD.... so:

- [ ] Can you share an ERD so that I can review the full database design? The database view in IntelliJ can produce this if you don't have a preferred way of generating it already.

**DAO**

GenericDao implemented. CRUD Dao unit testing completed on Sport.

- [ ] This may still be a work in progress: I don't know that this test is very useful - it basically make sure the same entity is returned by the same two calls. It'd be better if the returned entity were compared to an entity that you create in the test for comparison purposes. https://github.com/Rashad-636/sportsPerformancePredictor/blob/f7252715667525addd8abe417572d88ca10594b6/src/test/java/com/radams/entity/FavoriteTeamDaoTest.java#L29

- [ ] Unit tests have some empty methods. Tests should include tests for the relationships. For example, if a team is deleted, what happens to the sport, and vice versa. Make sure what should happen, does happen. 


**Log4J is implemented (no System.out.printlns)**

I noticed one place where the stack traces are being printed to the console: https://github.com/search?q=repo%3ARashad-636%2FsportsPerformancePredictor%20print&type=code. It'd be better to throw these exceptions up to the caller so they can  be logged. 

Regarding your question about the number of log files - a delete strategy can help with clean up of the files: https://github.com/mad-ent-java-f24/user-display-demo-code-V2/blob/a928ab5fd22003e92bd20202fd92af2666ec4d86/src/main/resources/log4j2.properties#L25-L32.  If this isn't quite what you are looking for, let me know! 

**Time log and Plan**

This is up-to-date through the beginning of week 8 (with items checked off in the plan).

- [ ] Consider adding more specific tasks for the upcoming weeks now that you likely have a better idea of what needs to be done.

**Other**

- [ ] A minor thing that I noticed: There's a long list of imports here, and in some other classes, that could be shortened by using a * to import all classes. For example: `import javax.servlet.*` https://github.com/Rashad-636/sportsPerformancePredictor/blob/f7252715667525addd8abe417572d88ca10594b6/src/main/java/com/radams/controller/Auth.java#L15-L41. 

****Checkpoint 2: not met**  - I'd just like to review the ERD and then this will be met.**  

Let me know if you have any questions!

**Comment by Rashad-636** [comment]
![IMG_4542 Medium](https://github.com/user-attachments/assets/113bf2d2-2976-4bbe-8f34-62003fad59f7)

Favoriteteam table will more than likely be renamed to User. This way I can have a list of all their favorite teams (team_id's)

**Comment by pawaitemadisoncollege** [comment]
Thanks for sharing the diagram @Rashad-636.  I agree with your idea to rename the Favoriteteam table to User.

I know much of this information can be obtained from the api, so it'll be up to you whether your store that data in tables or just get it from the service when you need it. The decision is based on things like: are you limited in the number of requests you can make, and does the data regularly change such that it's better to retrieve it from the service rather than store it.  A blend of storing some data and retrieving other data as needed is obviously an option too! 

**cp 2: met**

**Comment by Rashad-636** [comment]
I believe i am limited to 1000 requests per month and the data regular changes as games are played daily during the regular season. Sounds like a lot most of this data besides saving favorite teams needs to be retrieved rather than stored. I will make changes to my database after i do more brainstorming Thank you for the insight!On Oct 24, 2024, at 10:11 AM, Paula Waite ***@***.***> wrote:﻿
Thanks for sharing the diagram @Rashad-636.  I agree with your idea to rename the Favoriteteam table to User.
I know much of this information can be obtained from the api, so it'll be up to you whether your store that data in tables or just get it from the service when you need it. The decision is based on things like: are you limited in the number of requests you can make, and does the data regularly change such that it's better to retrieve it from the service rather than store it.  A blend of storing some data and retrieving other data as needed is obviously an option too!
cp 2: met
