### ISSUE TITLE
Week 8 ready for review

### ISSUE THREAD

**Issue by Rashad-636** [Rashad-636/sportsPerformancePredictor#3]
Consuming restful api's is a big part of my indie project and I was excited/curious to see how it would work. I was familiar with Postman previously but SoapUi is much better in my opinion. The use of the RoboPojo makes our job as a developer much easier and less time consuming which I though t was pretty neat. I have to look up how to include headers and parameters but that wan't too difficult. 

I'm getting to a decent point in my project to where I may be able to tie everything together.. possibly but I am very content with where I am although im playing a tiny bit of catch up!

Both unit tests pass but I feel as if there is an a better way to access the teamName instead of the .getTeams().getBody().get(0).getTeamName() syntax.  For now I am using the response java because it needs the statusCode and body before I can access the rest. Is there a way to bypass?

the Teams java class under the com.rapidapi package that was generated has the teamName variable and getTeamName method

![Screenshot 2024-10-23 at 3 07 18 PM (2)](https://github.com/user-attachments/assets/8f8d3850-a1ec-4295-bbc5-b512da3c8ce2)
![Screenshot 2024-10-23 at 3 07 25 PM (
![Screenshot 2024-10-23 at 3 10 53 PM (2)](https://github.com/user-attachments/assets/f6c84790-5804-4758-ac79-618fd92c113a)
2)](https://github.com/user-attachments/assets/74f154b1-16f6-4938-81ee-4aa81fd3992f)
![Screenshot 2024-10-23 at 3 07 28 PM (2)](https://github.com/user-attachments/assets/d0e1d626-a765-4f22-bd54-4a9d045abf1e)

**Comment by pawaitemadisoncollege** [comment]
Hi @Rashad-636 - wow, you certainly tackled a complex api for your first go at this! 

Sometimes service producers have very complicated responses, and it seems like this one is a good example of just that.  If the only way the service producer provides team names is using the endpoint you shared, then yes, you'll have to access it using .getTeams().getBody().get(0).getTeamName() syntax. 

To make your dao more useful for your project, you could have your dao do the work of turning the Response into a Team or maybe a List<Teams>, which it then returns. That way the caller doesn't have to do the work of parsing through the response: dao.getTeams().getBody().get(0).getTeamName(). 

It's good to see that you have using a property file on your radar rather than hard-coding the endpoint and your key.

Let me know if that answers your question!

Week 8: met
